server:
   port: 9999
   
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/edpas_java_fullstack
    username: postgres
    password: 12345

eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka/ 
      
security:  oauth2:    resource:      filter-order: 3
    client:      client-id: edpas-backend
      client-secret: edpas-backend-codex
      authorized-grant-types: password      scope: read,write      