server:
  port: 8099
  
eureka:
  client:
    #register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  host:
    connect-timeout-millis: 100000 
    socket-timeout-millis:  100000
  routes:
    uaa:
      path: /uaa/**
      sensitive-headers:
      service-id: EDPAS-MICROSERVICE-AUTH-SERVER        
    crud:
      path: /edpas-microservice-crud/**
      sensitive-headers:
      #service-id: EDPAS-MICROSERVICE-CRUD
      url: http://localhost:8080/        
    cr:
      path: /edpas-microservice-cr/**
      sensitive-headers:
      service-id: EDPAS-MICROSERVICE-CR
      #url: http://localhost:8081/
        