spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/edpas_java_fullstack
    username: postgres
    password: 12345

server:
   port: 8080
   
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka

# for security
security:  oauth2:    resource:      userInfoUri: http://localhost:9999/user 